[tool.semantic_release]
version_variable = "_version.py:__version__"
branch = "main"
description = "pytmac threat modelling as code tool"
readme = "README.md"
name = "pytmac"
keywords = ["python", "threat modelling", "security", "devsecops"]
