name: Semver Bump
on:
    push:
        branches:
            - "fix_ci_upload"
    workflow_dispatch:

jobs:
    auto-semver:
        runs-on: "ubuntu-latest"
        steps:
          - name: "Checkout code"
            uses: "actions/checkout@v3"
            with:
              fetch-depth: 0
          - name: "Python Semantic Release"
            uses: "python-semantic-release/python-semantic-release@master"
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
