name: Semver Bump
on:
    pull_request:
        branches:
            - "32-automatic-semver-bumping"
    workflow_dispatch:

jobs:
    unit-tests:
        runs-on: "ubuntu-latest"
        steps:
            - name: "Checkout code"
              uses: "actions/checkout@v3"
            - name: "Setup Python 3.11"
              uses: "actions/setup-python@v4"
              with:
                  python-version: "3.11"
            - name: "Install requirements"
              run: |
                pip3 install python-semantic-release
                semantic-release --help
                  
