name: Checkov
on:
  pull_request:
    branches:
      - "main"

permissions: read-all

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@8285a93b8ec14e277a8fe7e1b3faf7c59c77775f
        with:
          directory: .
          skip_check: CKV_OPENAPI_5,CKV_OPENAPI_4 # Demo swagger file
