name: Code Linting
on:
  pull_request:
    branches:
      - "main"

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@7bac8ad9627c5775917e8623ee2e342a98bb2dbf
        with:
          directory: .
