name: Checkov
on:
  pull_request:
    branches:
      - "main"

permissions: read-all

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@8ce9f49fa0d2a9c0c7aeccb7c3820ba7594d5afa
        with:
          directory: .
          skip_check: CKV_OPENAPI_5,CKV_OPENAPI_4 # Demo swagger file
