name: Code Linting
on:
  pull_request:
    branches:
        - "main"
    paths:
        - "**.py"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  code-linting:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"
      - name: "Code format"
        run: |
          pip3 install isort pylint black
          for file in $(find . -name "*.py" -not -path "./tests/*"); do
              python3 -m isort "$file"
              python3 -m black "c$file"
          done
      - name: "Commit linted files"
        uses: "stefanzweifel/git-auto-commit-action@v4"
        with:
          commit_message: "Linted and formatted files"
      - name: "Code linting"
        run: |
          pip3 install -r requirements.txt
          make lint
