name: Unit Tests
on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.py"
  workflow_dispatch:

jobs:
  code-linting:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"
      - name: "Install requirements"
        run: |
          pip3 install -r requirements.txt
      - name: "Unit tests"
        run: |
          python3 -m pytest
