name: Unit Tests
on:
    pull_request:
        branches:
            - "main"
    workflow_dispatch:

jobs:
    unit-tests:
        runs-on: "ubuntu-latest"
        strategy:
            matrix:
                python-version: [ "3.9", "3.10", "3.11" ]
        steps:
            - name: "Checkout code"
              uses: "actions/checkout@v3"
            - name: "Setup Python ${{ matrix.python-version }}"
              uses: "actions/setup-python@v4"
              with:
                  python-version: "${{ matrix.python-version }}"
            - name: "Install requirements"
              run: |
                  pip3 install -r requirements.txt
            - name: "Unit tests"
              run: |
                  mkdir tests/reports
                  make test
            - name: "Test coverage"
              run: |
                min_required_test_coverage=90
                test_coverage=$(python3 -m pytest --cov | grep "TOTAL" | awk {'print $4'} | sed 's/%//g')
                echo "Test coverage is $test_coverage"
                if (( $test_coverage < $min_required_test_coverage)); then
                  echo "Less than $min_required_test_coverage% test coverage"
                  exit 1
                fi
