name: Unit Tests
on:
    pull_request:
        branches:
            - "main"
    workflow_dispatch:

jobs:
    unit-tests:
        runs-on: "ubuntu-latest"
        strategy:
            matrix:
                python-version: [ "3.9", "3.10", "3.11" ]
        steps:
            - name: "Checkout code"
              uses: "actions/checkout@v3"
            - name: "Setup Python ${{ matrix.python-version }}"
              uses: "actions/setup-python@v4"
              with:
                  python-version: "${{ matrix.python-version }}"
            - name: "Install requirements"
              run: |
                  pip3 install -r requirements.txt
            - name: "Unit tests"
              run: |
                  mkdir tests/reports
                  python3 -m pytest
            - name: "Test coverage"
              run: |
                if (( python3 -m pytest --cov | grep "TOTAL" | awk {'print $4'} | sed 's/%//g' < 95)); then
                  echo "Less than 95% test coverage"
                  exit 1
                fi
